## ********************************************************************* ##
## Copyright 2016-2019                                                   ##
## Portland Community College                                            ##
##                                                                       ##
## This file is part of Open Resources for Community College Algebra     ##
## (ORCCA).                                                              ##
## ********************************************************************* ##


#######################
# DO NOT EDIT THIS FILE
#######################

#   1) Make a copy of Makefile.paths.original
#      as Makefile.paths, which git will ignore.
#   2) Edit Makefile.paths to provide full paths to the root folders
#      of your local clones of the project repository and the mathbook
#      repository as described below.
#   3) The files Makefile and Makefile.paths.original
#      are managed by git revision control and any edits you make to
#      these will conflict. You should only be editing Makefile.paths.

##############
# Introduction
##############

# This is not a "true" makefile, since it does not
# operate on dependencies.  It is more of a shell
# script, sharing common configurations

######################
# System Prerequisites
######################

#   install         (system tool to make directories)
#   xsltproc        (xml/xsl text processor)
#   java,jingtrang  (only for schema validation)
#   <helpers>       (PDF viewer, web browser, pager, Sage executable, etc)

#####
# Use
#####

#	A) Navigate to the location of this file
#	B) At command line:  make <some-recipe-from-the-options-below>

##################################################
# The included file contains customized versions
# of locations of the principal components of this
# project and names of various helper executables
##################################################
include Makefile.paths

###################################
# These paths are subdirectories of
# the project distribution
###################################
SRC       = $(PRJ)/src
IMGSRC    = $(SRC)/images
OUTPUT    = $(PRJ)/output
PUB       = $(PRJ)/publication
XSL       = $(PRJ)/xsl

# The project's root file
MAINFILE  = $(SRC)/orcca.ptx

# Local translation stylesheets
PRINT      = $(XSL)/orcca-print.xsl
ODDANS     = $(XSL)/orcca-odd-answers.xsl
SCRNPDF    = $(XSL)/orcca-screenpdf.xsl
HTML       = $(XSL)/orcca-html.xsl

# The project's styling files
PUBFILE   = $(PUB)/publication.xml
CSS       = $(PUB)/css

# These paths are subdirectories of
# the PreTeXt distribution
PTXXSL = $(PTX)/xsl

# These paths are subdirectories of the output
# folder for different output formats
PRINTOUT   = $(OUTPUT)/print
ODDANSOUT  = $(OUTPUT)/odd-answers
SCRNPDFOUT = $(OUTPUT)/screenpdf
HTMLOUT    = $(OUTPUT)/html
WWOUT      = $(OUTPUT)/webwork-representations
IMGOUT     = $(OUTPUT)/images
PGOUT      = $(OUTPUT)/pg
PRVOUT     = $(OUTPUT)/preview

# The WeBWorK server we use
#SERVER = "(https://webwork.runestone.academy,anonymous,anonymous,anonymous,anonymous)"
#SERVER = "(https://webwork-dev.aimath.org,anonymous,anonymous,anonymous,anonymous)"
SERVER = "(https://webwork.pcc.edu,orcca,orcca,anonymous,orcca)"
#SERVER = http://localhost

webwork-representations:
	date
	-rm -r $(WWOUT) || :
	install -d $(WWOUT)
	$(PTX)/pretext/pretext -vv -a -c webwork -d $(WWOUT) -s $(SERVER) $(MAINFILE)
	date

pg:
	-rm -r $(PGOUT) || :
	install -d $(PGOUT)
	cd $(PGOUT); \
	xsltproc --xinclude --stringparam publisher $(PUBFILE) --stringparam chunk.level 2 $(PTXXSL)/pretext-ww-problem-sets.xsl $(MAINFILE)

print-pretext:
	install -d $(OUTPUT)
	-rm -r $(PRINTOUT) || :
	install -d $(PRINTOUT)
	install -d $(PRINTOUT)/images
	install -d $(IMGOUT)
	install -d $(IMGSRC)
	cp -a $(WWOUT)/*.png $(PRINTOUT)/images || :
	cp -a $(PRVOUT)/*.png $(PRINTOUT)/images || :
	cp -a $(IMGSRC) $(PRINTOUT) || :
	cd $(PRINTOUT); \
	xsltproc --xinclude --stringparam publisher $(PUBFILE) $(PTXXSL)/pretext-latex.xsl $(MAINFILE) > orcca.tex; \
	xelatex orcca.tex; \
	xelatex orcca.tex; \

pdf-nopost:
	install -d $(OUTPUT)
	-rm -r $(PRINTOUT) || :
	install -d $(PRINTOUT)
	install -d $(PRINTOUT)/images
	install -d $(IMGOUT)
	install -d $(IMGSRC)
	cp -a $(WWOUT)/*.png $(PRINTOUT)/images || :
	cp -a $(PRVOUT)/*.png $(PRINTOUT)/images || :
	cp -a $(IMGSRC) $(PRINTOUT) || :
	cd $(PRINTOUT); \
	xsltproc --xinclude --stringparam publisher $(PUBFILE) --stringparam toc.level 3 --stringparam latex.print 'yes' --stringparam latex.pageref 'no' --stringparam latex.sides 'two' $(PRINT) $(MAINFILE) > orcca.tex; \
	xelatex orcca.tex; \
	xelatex orcca.tex; \

#should be done after pdf
odd-answers:
	cd $(PRINTOUT); \
	xsltproc --xinclude --stringparam publisher $(PUBFILE) --stringparam toc.level 3 --stringparam latex.pageref 'no' --stringparam latex.sides 'one' $(XSL)/orcca-odd-answers.xsl $(MAINFILE) > orcca-odd-answers.tex; \
	xelatex orcca-odd-answers.tex; \
	xelatex orcca-odd-answers.tex; \
	xelatex orcca-odd-answers.tex;

screenpdf:
	install -d $(OUTPUT)
	-rm -r $(SCRNPDFOUT) || :
	install -d $(SCRNPDFOUT)
	install -d $(SCRNPDFOUT)/images
	install -d $(IMGOUT)
	install -d $(IMGSRC)
	cp -a $(WWOUT)/*.png $(SCRNPDFOUT)/images || :
	cp -a $(PRVOUT)/*.png $(SCRNPDFOUT)/images || :
	cp -a $(IMGSRC) $(SCRNPDFOUT) || :
	cd $(SCRNPDFOUT); \
	xsltproc --xinclude --stringparam publisher $(PUBFILE) $(SCRNPDF) $(MAINFILE)  > orcca-screenpdf.tex; \
	cp orcca-screenpdf.tex orcca-screenpdf-no-regex.tex; \
	perl -p0i -e 's/(\\end{inlineexercise}\n)(\w)/\1\\noindent \2/g' orcca-screenpdf.tex; \
	perl -p0i -e 's/(\\end{example}\n)(\w)/\1\\noindent \2/g' orcca-screenpdf.tex; \
	perl -p0i -e 's/(\\end{figure}\n)(\w)/\1\\noindent \2/g' orcca-screenpdf.tex; \
	perl -p0i -e 's/(\\end{sidebyside}%\n\\par\n)(\w)/\1\\noindent \2/g' orcca-screenpdf.tex; \
	echo 'GLOBAL SPACING'; \
	echo 'Next line removes \leavevmode when it comes right before an enumerate'; \
	perl -p0i -e 's/\\leavevmode%\n(\\begin{enumerate})/\1/g' orcca-screenpdf.tex; \
	echo 'Next line removes \leavevmode when it comes right before a multicols'; \
	perl -p0i -e 's/\\leavevmode%\n(\\begin{multicols})/\1/g' orcca-screenpdf.tex; \
	echo 'Next line removes \par when it comes right before an equation'; \
	perl -p0i -e 's/\\par\n(%\n\\begin\{equation)/\1/g' orcca-screenpdf.tex; \
	echo 'Next two lines attempt to prevent pagebreaks after an "Explanation" title; not always with success'; \
	perl -p0i -e 's/(\\noindent\\textbf\{Explanation\}.*?\n(((?!\\begin).)*?\n)*?)(.*\\par)/\\makeatletter\\\@beginparpenalty=10000\\makeatother\n\1\\makeatletter\\\@beginparpenalty=-51\\makeatother\n\4/g' orcca-screenpdf.tex; \
	perl -p0i -e 's/(\\noindent\\textbf\{Explanation\}.*?\n(((?!\\par).)*?\n)*?\\end(?!({tikzpicture}|{aligned}|{alignedat})).*?\n)/\\makeatletter\\\@beginparpenalty=10000\\makeatother\n\1\\makeatletter\\\@beginparpenalty=-51\\makeatother\n/g' orcca-screenpdf.tex; \
	echo 'Next line attempts to prevent pagebreaks after an "Exercises" starts; not always with success'; \
	perl -p0i -e 's/(\\begin\{exercises-subsection\}\{Exercises\}.*?\n(.*?\n)*?\\end\{divisionexercise\}%\n)/\\makeatletter\\\@beginparpenalty=10000\\makeatother\n\1\\makeatletter\\\@beginparpenalty=-51\\makeatother\n/g' orcca-screenpdf.tex; \
	echo 'Next two lines look for a list in an exercise where the exercise starts, and gets first line to start on exercise opening line'; \
	perl -p0i -e 's/^(\\begin{divisionexerciseegcol}.*?\n\\begin{enumerate)(}\[label=\\alph\*\.)(\]\n)((.*?\n)*?\\end{enumerate)}/\1\*\2,itemjoin=\{\\vspace\{0\.5pc\}\\newline\},afterlabel=\{\\hspace\{1ex\}\}\3\4\*}\\vspace{0.5pc}\n\n/gm' orcca-screenpdf.tex; \
	perl -p0i -e 's/^(\\begin{divisionexerciseegcol}.*?\n\\hypertarget{.*?}\{\}%\n\\begin{enumerate)(}\[label=\\alph\*\.)(\]\n)((.*?\n)*?\\end{enumerate)}/\1\*\2,itemjoin=\{\\vspace\{0\.5pc\}\\newline\},afterlabel=\{\\hspace\{1ex\}\}\3\4\*}\\vspace{0.5pc}\n\n/gm' orcca-screenpdf.tex; \
	echo 'IMAGE WIDTH ADJUSTMENT'; \
	echo 'WeBWorK images in a multicolumn list or exercisegroup need these sizing adjustments, effectively resizing them to 100%. The for loops are just to make the regex search and replace repeat enough times to hit all instances within a list or exerisegroup'; \
	for i in {1..3}; do perl -p0i -e 's/^(\\begin{inlineexercise}.*?(((?!inlineexercise).)*\n)*?\\begin{multicols}\{3\}\n(((?!multicols).)*\n)*?\\begin{sidebyside}\{1\})\{0\.3\}\{0\.3\}\{0\}%\n(\\begin{sbspanel})\{0\.4\}/\1\{0\}\{0\}\{0\}%\n\6\{1\}/gm' orcca-screenpdf.tex; done; \
	for i in {1..6}; do perl -p0i -e 's/^(\\begin{exercisegroup}\n(((?!exercisegroup).)*\n)*?\\begin{sidebyside}\{1\})\{0\.3\}\{0\.3\}\{0\}%\n(\\begin{sbspanel})\{0\.4\}/\1\{0\}\{0\}\{0\}%\n\4\{1\}/gm' orcca-screenpdf.tex; done; \
	for i in {1..28}; do perl -p0i -e 's/^(\\begin{exercisegroupcol}\{[234]\}\n(((?!exercisegroup).)*\n)*?\\begin{sidebyside}\{1\})\{0\.3\}\{0\.3\}\{0\}%\n(\\begin{sbspanel})\{0\.4\}/\1\{0\}\{0\}\{0\}%\n\4\{1\}/gm' orcca-screenpdf.tex; done; \
	perl -p0i -e 's/^(The pie chart represents a collector.s collection of signatures from various artists.%\n\\begin{sidebyside}\{1\}){0\.166666666666667}{0\.166666666666667}\{0\}%\n\\begin{sbspanel}{0\.666666666666667}/\1\{0\}\{0\}\{0\}%\n\\begin{sbspanel}\{1\}/gm' orcca-screenpdf.tex; \
	perl -p0i -e 's/^((The pie chart .* artists.|The following is a nutrition .* box.|A community college .* the survey.)%\n\\begin{sidebyside}\{1\}){0\.166666666666667}{0\.166666666666667}\{0\}%\n\\begin{sbspanel}{0\.666666666666667}/\1\{0\}\{0\}\{0\}%\n\\begin{sbspanel}\{1\}/gm' orcca-screenpdf.tex; \
	echo 'SYSTEMS OF EQUATIONS IN DISPLAY MODE'; \
	for i in {1..20}; do perl -p0i -e 's/^(\\textbf{Using a Graph to Solve a System}\\space\\space%\nUse a graph to solve the system of equations.%\n\\begin{exercisegroupcol}\{\d\}\n(.*?\n)*?\\begin{divisionexerciseegcol}.*?\n(.*?\n)*?)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*})/\1\\begin{fleqn}\[1em\]\n\\leavevmode\\vspace\*\{-\\dimexpr\\baselineskip\+\\abovedisplayskip\\relax}\4\\end{fleqn}\\newline/m' orcca-screenpdf.tex; done; \
	for i in {1..50}; do perl -p0i -e 's/^(\\textbf{Solving System of Equations Using Substitution}\\space\\space%\nSolve the following system of equations.%\n\\begin{exercisegroupcol}\{\d\}\n(.*?\n)*?\\begin{divisionexerciseegcol}.*?\n(.*?\n)*?)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*})/\1\\begin{fleqn}\[1em\]\n\\leavevmode\\vspace\*\{-\\dimexpr\\baselineskip\+\\abovedisplayskip\\relax}\4\\end{fleqn}\\newline/m' orcca-screenpdf.tex; done; \
	for i in {1..32}; do perl -p0i -e 's/^(\\textbf{Solving System of Equations by Elimination}\\space\\space%\nSolve the following system of equations.%\n\\begin{exercisegroupcol}\{\d\}\n(.*?\n)*?\\begin{divisionexerciseegcol}.*?\n(.*?\n)*?)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*})/\1\\begin{fleqn}\[1em\]\n\\leavevmode\\vspace\*\{-\\dimexpr\\baselineskip\+\\abovedisplayskip\\relax}\4\\end{fleqn}\\newline/m' orcca-screenpdf.tex; done; \
	for i in {1..8}; do perl -p0i -e 's/^(\\textbf{Solving Systems of Linear Equations by Graphing}\\space\\space%\nUse a graph to solve the system of equations.%\n\\begin{exercisegroupcol}\{\d\}\n(.*?\n)*?\\begin{divisionexerciseegcol}.*?\n(.*?\n)*?)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*})/\1\\begin{fleqn}\[1em\]\n\\leavevmode\\vspace\*\{-\\dimexpr\\baselineskip\+\\abovedisplayskip\\relax}\4\\end{fleqn}\\newline/m' orcca-screenpdf.tex; done; \
	for i in {1..8}; do perl -p0i -e 's/^(\\textbf{Substitution}\\space\\space%\nSolve the following system of equations.%\n\\begin{exercisegroupcol}\{\d\}\n(.*?\n)*?\\begin{divisionexerciseegcol}.*?\n(.*?\n)*?)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*})/\1\\begin{fleqn}\[1em\]\n\\leavevmode\\vspace\*\{-\\dimexpr\\baselineskip\+\\abovedisplayskip\\relax}\4\\end{fleqn}\\newline/m' orcca-screenpdf.tex; done; \
	for i in {1..8}; do perl -p0i -e 's/^(\\textbf{Elimination}\\space\\space%\nSolve the following system of equations.%\n\\begin{exercisegroupcol}\{\d\}\n(.*?\n)*?\\begin{divisionexerciseegcol}.*?\n(.*?\n)*?)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*})/\1\\begin{fleqn}\[1em\]\n\\leavevmode\\vspace\*\{-\\dimexpr\\baselineskip\+\\abovedisplayskip\\relax}\4\\end{fleqn}\\newline/m' orcca-screenpdf.tex; done; \
	perl -p0i -e 's/^(\\begin{example}[^\n]*?example:VQz}%\n.*?\n.*?\n.*?\n)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*}\n)%\n\\item\{\}%\n(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*}\n)/\1\\begin{fleqn}\[1em\]\n\2\\end{fleqn}\n%\n\\item\{\}%\n\\begin{fleqn}\[1em\]\n\4\\end{fleqn}\n/m' orcca-screenpdf.tex; \
	echo 'REMOVE ALL ANSWER BLANKS AND EQUALS SIGNS THAT ARE IN SHORT LINES LIKE 1+2=___ '; \
	perl -p0i -e 's/^(\\\(((?!(\\\)|text)).)*) *=([ \n}]*\\\)) *\\fillin{\d+} *\.?%\n/\1\4%\n/gm' orcca-screenpdf.tex; \
	perl -pi -e 's/^(\\item\{\}\\\(((?!(\\\)|text)).)*) *=([ }]*\\\)) *\\fillin{\d+} *\.?%\n/\1\4%\n/g' orcca-screenpdf.tex; \
	perl -pi -e 's/^(\\\(((?!(\\\)|text)).)*\\\)) *= *\\fillin{\d+} *\.?%\n/\1%\n/g' orcca-screenpdf.tex; \
	perl -pi -e 's/^(\\item\{\}\\\(((?!(\\\)|text)).)*\\\)) *= *\\fillin{\d+} *\.?%\n/\1%\n/g' orcca-screenpdf.tex; \
	perl -pi -e 's/^(\\\(((?!(\\\)|text)).)*) *=\{\}([ }]*\\\)) *\\fillin\{\d+\} *\.?%\n/\1\4%\n/g' orcca-screenpdf.tex; \
	perl -pi -e 's/^(\\\(((?!(\\\)|text)).)*) *\\approx([ }]*\\\)) *\\fillin{\d+} *\.?%\n/\1\4%\n/g' orcca-screenpdf.tex; \
	perl -p0i -e 's/^(\\\(((?!(\\\)|text)).)*) *\\approx([ \n}]*\\\)) *\\fillin{\d+} *\.?%\n/\1\4%\n/gm' orcca-screenpdf.tex; \
	perl -pi -e 's/^(\\item\{\}\\\(((?!(\\\)|text)).)*) *\\approx([ }]*\\\)) *\\fillin{\d+} *\.?%\n/\1\4%\n/g' orcca-screenpdf.tex; \
	perl -pi -e 's/^(\\\(((?!(\\\)|text)).)*\\\)) *\\approx *\\fillin{\d+} *\.?%\n/\1%\n/g' orcca-screenpdf.tex; \
	perl -pi -e 's/^(\\item\{\}\\\(((?!(\\\)|text)).)*\\\)) *\\approx *\\fillin{\d+} *\.?%\n/\1%\n/g' orcca-screenpdf.tex; \
	perl -pi -e 's/^(\\\(((?!(\\\)|text)).)*) *\\approx\{\}([ }]*\\\)) *\\fillin\{\d+\} *\.?%\n/\1\4%\n/g' orcca-screenpdf.tex; \
	perl -p0i -e 's/^\\\(x\\\)%\n/%\n/gm' orcca-screenpdf.tex; \
	echo 'EDGE INDEXING AND PAGE RENUMBERING'; \
	perl -pi -e 's/^(\\begin{partptx}{Linear Equations and Lines})/\\xpatchcmd{\\part}{\\thispagestyle{plain}}{\\begin{tikzpicture}\[remember picture,overlay\]\\draw \[color=emerald, fill=emerald\] \(\[xshift=-0.625in\]current page\.north east\) rectangle \(current page\.south east\);\\end{tikzpicture}\\break\\pagenumbering{arabic}\\thispagestyle{plain}}\{\}\{\}\\xpatchcmd{\\\@endpart}{\\vfil\\newpage}{\\vfil\\newpage}\{\}\{\}\n\1/' orcca-screenpdf.tex; \
	perl -pi -e 's/^(\\begin{partptx}{Preparation for STEM})/\\xpatchcmd{\\part}{\\thispagestyle{plain}}{\\begin{tikzpicture}\[remember picture,overlay\]\\draw \[color=turquoise, fill=turquoise\] \(\[xshift=-0.625in\]current page\.north east\) rectangle \(current page\.south east\);\\end{tikzpicture}\\break\\pagenumbering{arabic}\\thispagestyle{plain}}\{\}\{\}\\xpatchcmd{\\\@endpart}{\\vfil\\newpage}{\\vfil\\newpage}\{\}\{\}\n\1/' orcca-screenpdf.tex; \
	perl -pi -e 's/^(\\begin{partptx}{Preparation for College Algebra})/\\xpatchcmd{\\part}{\\thispagestyle{plain}}{\\begin{tikzpicture}\[remember picture,overlay\]\\draw \[color=amethyst, fill=amethyst\] \(\[xshift=-0.625in\]current page\.north east\) rectangle \(current page\.south east\);\\end{tikzpicture}\\break\\pagenumbering{arabic}\\thispagestyle{plain}}\{\}\{\}\\xpatchcmd{\\\@endpart}{\\vfil\\newpage}{\\vfil\\newpage}\{\}\{\}\n\1/' orcca-screenpdf.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=emerald,   fill=emerald  ] ([xshift=-0.625in] \$$ \(current page.north east\) \$$ ) rectangle ( \$$  \(A\)!1\/13!\(B\)          \$$ );\\end{tikzpicture}\n/m' orcca-screenpdf.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=emerald,   fill=emerald  ] ([xshift=-0.625in] \$$  \(A\)!2\/13-1\/13!\(B\)    \$$ ) rectangle ( \$$  \(A\)!2\/13!\(B\)          \$$ );\\end{tikzpicture}\n/m' orcca-screenpdf.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=emerald,   fill=emerald  ] ([xshift=-0.625in] \$$  \(A\)!3\/13-1\/13!\(B\)    \$$ ) rectangle ( \$$  \(A\)!3\/13!\(B\)          \$$ );\\end{tikzpicture}\n/m' orcca-screenpdf.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=emerald,   fill=emerald  ] ([xshift=-0.625in] \$$  \(A\)!4\/13-1\/13!\(B\)    \$$ ) rectangle ( \$$  \(A\)!4\/13!\(B\)          \$$ );\\end{tikzpicture}\n/m' orcca-screenpdf.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=turquoise, fill=turquoise] ([xshift=-0.625in] \$$  \(A\)!5\/13-1\/13!\(B\)    \$$ ) rectangle ( \$$  \(A\)!5\/13!\(B\)          \$$ );\\end{tikzpicture}\n/m' orcca-screenpdf.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=turquoise, fill=turquoise] ([xshift=-0.625in] \$$  \(A\)!6\/13-1\/13!\(B\)    \$$ ) rectangle ( \$$  \(A\)!6\/13!\(B\)          \$$ );\\end{tikzpicture}\n/m' orcca-screenpdf.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=turquoise, fill=turquoise] ([xshift=-0.625in] \$$  \(A\)!7\/13-1\/13!\(B\)    \$$ ) rectangle ( \$$  \(A\)!7\/13!\(B\)          \$$ );\\end{tikzpicture}\n/m' orcca-screenpdf.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=turquoise, fill=turquoise] ([xshift=-0.625in] \$$  \(A\)!8\/13-1\/13!\(B\)    \$$ ) rectangle ( \$$  \(A\)!8\/13!\(B\)          \$$ );\\end{tikzpicture}\n/m' orcca-screenpdf.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=turquoise, fill=turquoise] ([xshift=-0.625in] \$$  \(A\)!9\/13-1\/13!\(B\)    \$$ ) rectangle ( \$$  \(A\)!9\/13!\(B\)          \$$ );\\end{tikzpicture}\n/m' orcca-screenpdf.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=amethyst,  fill=amethyst ] ([xshift=-0.625in] \$$ \(A\)!10\/13-1\/13!\(B\)    \$$ ) rectangle ( \$$ \(A\)!10\/13!\(B\)          \$$ );\\end{tikzpicture}\n/m' orcca-screenpdf.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=amethyst,  fill=amethyst ] ([xshift=-0.625in] \$$ \(A\)!11\/13-1\/13!\(B\)    \$$ ) rectangle ( \$$ \(A\)!11\/13!\(B\)          \$$ );\\end{tikzpicture}\n/m' orcca-screenpdf.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=amethyst,  fill=amethyst ] ([xshift=-0.625in] \$$ \(A\)!12\/13-1\/13!\(B\)    \$$ ) rectangle ( \$$ \(A\)!12\/13!\(B\)          \$$ );\\end{tikzpicture}\n/m' orcca-screenpdf.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=amethyst,  fill=amethyst ] ([xshift=-0.625in] \$$ \(A\)!13\/13-1\/13!\(B\)    \$$ ) rectangle ( \$$ \(current page.south east\) \$$ );\\end{tikzpicture}\n/m' orcca-screenpdf.tex; \
	perl -pi -e 's/^(\\begin{appendixptx}.*?\n)/\\cleardoublepage\n\\pagenumbering{arabic}\n\\renewcommand{\\thepage}{\\thechapter\\arabic{page}}\n\1\\begin{tikzpicture}\[remember picture,overlay\]\\draw \[color=ruby, fill=ruby\] \(\[xshift=-0.625in\]current page.north east\) rectangle \(current page\.south east\);\\end{tikzpicture}\n/g' orcca-screenpdf.tex; \

pdf-edition2:
	install -d $(OUTPUT)
	-rm -r $(PRINTOUT) || :
	install -d $(PRINTOUT)
	install -d $(PRINTOUT)/images
	install -d $(IMGOUT)
	install -d $(IMGSRC)
	cp -a $(WWOUT)/*.png $(PRINTOUT)/images || :
	cp -a $(PRVOUT)/*.png $(PRINTOUT)/images || :
	cp -a $(IMGSRC) $(PRINTOUT) || :
	cd $(PRINTOUT); \
	xsltproc --xinclude --stringparam publisher $(PUBFILE) $(XSL)/orcca-print.xsl $(MAINFILE) > orcca.tex; \
	cp orcca.tex orcca-no-regex.tex; \
	echo 'DO NOT INDENT IN SOME PLACES'; \
	perl -p0i -e 's/(\\end{inlineexercise}\n)(\w)/\1\\noindent \2/g' orcca.tex; \
	perl -p0i -e 's/(\\end{example}\n)(\w)/\1\\noindent \2/g' orcca.tex; \
	perl -p0i -e 's/(\\end{figure}\n)(\w)/\1\\noindent \2/g' orcca.tex; \
	perl -p0i -e 's/(\\end{sidebyside}%\n\\par\n)(\w)/\1\\noindent \2/g' orcca.tex; \
	echo 'GLOBAL SPACING'; \
	echo 'Next line removes \leavevmode when it comes right before an enumerate'; \
	perl -p0i -e 's/\\leavevmode%\n(\\begin{enumerate})/\1/g' orcca.tex; \
	echo 'Next line removes \leavevmode when it comes right before a multicols'; \
	perl -p0i -e 's/\\leavevmode%\n(\\begin{multicols})/\1/g' orcca.tex; \
	echo 'Next line removes \par when it comes right before an equation'; \
	perl -p0i -e 's/\\par\n(%\n\\begin\{equation)/\1/g' orcca.tex; \
	echo 'Next two lines attempt to prevent pagebreaks after an "Explanation" title; not always with success'; \
	perl -p0i -e 's/(\\noindent\\textbf\{Explanation\}.*?\n(((?!\\begin).)*?\n)*?)(.*\\par)/\\makeatletter\\\@beginparpenalty=10000\\makeatother\n\1\\makeatletter\\\@beginparpenalty=-51\\makeatother\n\4/g' orcca.tex; \
	perl -p0i -e 's/(\\noindent\\textbf\{Explanation\}.*?\n(((?!\\par).)*?\n)*?\\end(?!({tikzpicture}|{aligned}|{alignedat})).*?\n)/\\makeatletter\\\@beginparpenalty=10000\\makeatother\n\1\\makeatletter\\\@beginparpenalty=-51\\makeatother\n/g' orcca.tex; \
	echo 'Next line attempts to prevent pagebreaks after an "Exercises" starts; not always with success'; \
	perl -p0i -e 's/(\\begin\{exercises-subsection\}\{Exercises\}.*?\n(.*?\n)*?\\end\{divisionexercise\}%\n)/\\makeatletter\\\@beginparpenalty=10000\\makeatother\n\1\\makeatletter\\\@beginparpenalty=-51\\makeatother\n/g' orcca.tex; \
	echo 'Next two lines look for a list in an exercise where the exercise starts, and gets first line to start on exercise opening line'; \
	perl -p0i -e 's/^(\\begin{divisionexerciseegcol}.*?\n\\begin{enumerate)(}\[label=\\alph\*\.)(\]\n)((.*?\n)*?\\end{enumerate)}/\1\*\2,itemjoin=\{\\vspace\{0\.5pc\}\\newline\},afterlabel=\{\\hspace\{1ex\}\}\3\4\*}\\vspace{0.5pc}\n\n/gm' orcca.tex; \
	perl -p0i -e 's/^(\\begin{divisionexerciseegcol}.*?\n\\hypertarget{.*?}\{\}%\n\\begin{enumerate)(}\[label=\\alph\*\.)(\]\n)((.*?\n)*?\\end{enumerate)}/\1\*\2,itemjoin=\{\\vspace\{0\.5pc\}\\newline\},afterlabel=\{\\hspace\{1ex\}\}\3\4\*}\\vspace{0.5pc}\n\n/gm' orcca.tex; \
	echo 'IMAGE WIDTH ADJUSTMENT'; \
	echo 'WeBWorK images in a multicolumn list or exercisegroup need these sizing adjustments, effectively resizing them to 100%. The for loops are just to make the regex search and replace repeat enough times to hit all instances within a list or exerisegroup'; \
	for i in {1..3}; do perl -p0i -e 's/^(\\begin{inlineexercise}.*?(((?!inlineexercise).)*\n)*?\\begin{multicols}\{3\}\n(((?!multicols).)*\n)*?\\begin{sidebyside}\{1\})\{0\.3\}\{0\.3\}\{0\}%\n(\\begin{sbspanel})\{0\.4\}/\1\{0\}\{0\}\{0\}%\n\6\{1\}/gm' orcca.tex; done; \
	for i in {1..6}; do perl -p0i -e 's/^(\\begin{exercisegroup}\n(((?!exercisegroup).)*\n)*?\\begin{sidebyside}\{1\})\{0\.3\}\{0\.3\}\{0\}%\n(\\begin{sbspanel})\{0\.4\}/\1\{0\}\{0\}\{0\}%\n\4\{1\}/gm' orcca.tex; done; \
	for i in {1..28}; do perl -p0i -e 's/^(\\begin{exercisegroupcol}\{[234]\}\n(((?!exercisegroup).)*\n)*?\\begin{sidebyside}\{1\})\{0\.3\}\{0\.3\}\{0\}%\n(\\begin{sbspanel})\{0\.4\}/\1\{0\}\{0\}\{0\}%\n\4\{1\}/gm' orcca.tex; done; \
	perl -p0i -e 's/^(The pie chart represents a collector.s collection of signatures from various artists.%\n\\begin{sidebyside}\{1\}){0\.166666666666667}{0\.166666666666667}\{0\}%\n\\begin{sbspanel}{0\.666666666666667}/\1\{0\}\{0\}\{0\}%\n\\begin{sbspanel}\{1\}/gm' orcca.tex; \
	perl -p0i -e 's/^((The pie chart .* artists.|The following is a nutrition .* box.|A community college .* the survey.)%\n\\begin{sidebyside}\{1\}){0\.166666666666667}{0\.166666666666667}\{0\}%\n\\begin{sbspanel}{0\.666666666666667}/\1\{0\}\{0\}\{0\}%\n\\begin{sbspanel}\{1\}/gm' orcca.tex; \
	echo 'SYSTEMS OF EQUATIONS IN DISPLAY MODE'; \
	for i in {1..20}; do perl -p0i -e 's/^(\\textbf{Using a Graph to Solve a System}\\space\\space%\nUse a graph to solve the system of equations.%\n\\begin{exercisegroupcol}\{\d\}\n(.*?\n)*?\\begin{divisionexerciseegcol}.*?\n(.*?\n)*?)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*})/\1\\begin{fleqn}\[1em\]\n\\leavevmode\\vspace\*\{-\\dimexpr\\baselineskip\+\\abovedisplayskip\\relax}\4\\end{fleqn}\\newline/m' orcca.tex; done; \
	for i in {1..50}; do perl -p0i -e 's/^(\\textbf{Solving System of Equations Using Substitution}\\space\\space%\nSolve the following system of equations.%\n\\begin{exercisegroupcol}\{\d\}\n(.*?\n)*?\\begin{divisionexerciseegcol}.*?\n(.*?\n)*?)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*})/\1\\begin{fleqn}\[1em\]\n\\leavevmode\\vspace\*\{-\\dimexpr\\baselineskip\+\\abovedisplayskip\\relax}\4\\end{fleqn}\\newline/m' orcca.tex; done; \
	for i in {1..32}; do perl -p0i -e 's/^(\\textbf{Solving System of Equations by Elimination}\\space\\space%\nSolve the following system of equations.%\n\\begin{exercisegroupcol}\{\d\}\n(.*?\n)*?\\begin{divisionexerciseegcol}.*?\n(.*?\n)*?)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*})/\1\\begin{fleqn}\[1em\]\n\\leavevmode\\vspace\*\{-\\dimexpr\\baselineskip\+\\abovedisplayskip\\relax}\4\\end{fleqn}\\newline/m' orcca.tex; done; \
	for i in {1..8}; do perl -p0i -e 's/^(\\textbf{Solving Systems of Linear Equations by Graphing}\\space\\space%\nUse a graph to solve the system of equations.%\n\\begin{exercisegroupcol}\{\d\}\n(.*?\n)*?\\begin{divisionexerciseegcol}.*?\n(.*?\n)*?)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*})/\1\\begin{fleqn}\[1em\]\n\\leavevmode\\vspace\*\{-\\dimexpr\\baselineskip\+\\abovedisplayskip\\relax}\4\\end{fleqn}\\newline/m' orcca.tex; done; \
	for i in {1..8}; do perl -p0i -e 's/^(\\textbf{Substitution}\\space\\space%\nSolve the following system of equations.%\n\\begin{exercisegroupcol}\{\d\}\n(.*?\n)*?\\begin{divisionexerciseegcol}.*?\n(.*?\n)*?)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*})/\1\\begin{fleqn}\[1em\]\n\\leavevmode\\vspace\*\{-\\dimexpr\\baselineskip\+\\abovedisplayskip\\relax}\4\\end{fleqn}\\newline/m' orcca.tex; done; \
	for i in {1..8}; do perl -p0i -e 's/^(\\textbf{Elimination}\\space\\space%\nSolve the following system of equations.%\n\\begin{exercisegroupcol}\{\d\}\n(.*?\n)*?\\begin{divisionexerciseegcol}.*?\n(.*?\n)*?)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*})/\1\\begin{fleqn}\[1em\]\n\\leavevmode\\vspace\*\{-\\dimexpr\\baselineskip\+\\abovedisplayskip\\relax}\4\\end{fleqn}\\newline/m' orcca.tex; done; \
	perl -p0i -e 's/^(\\begin{example}[^\n]*?example:VQz}%\n.*?\n.*?\n.*?\n)(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*}\n)%\n\\item\{\}%\n(\\begin{equation\*}\n(.*?\n)*?\\end{equation\*}\n)/\1\\begin{fleqn}\[1em\]\n\2\\end{fleqn}\n%\n\\item\{\}%\n\\begin{fleqn}\[1em\]\n\4\\end{fleqn}\n/m' orcca.tex; \
	echo 'INDIVIDUAL INSERTIONS'; \
	echo 'Insert a \par following an aside, before a sidebyside'; \
	perl -pi -e 's/(\{Figure\~\\ref\{x:figure:figure-balance-scale\}\} shows the scale\.\%\n)/\1\\par\n/' orcca.tex; \
	echo 'Insert a \par following the last reading question which follows an aside from pages earlier causing problems'; \
	perl -p0i -e 's/(Every time you solve an equation, there is something you should do to guarantee success\. Describe what that thing is that you should do\.%\n\\end{divisionexercise}%\n)/\1\\par\n/' orcca.tex; \
	echo 'Insert a \par following an aside that is causing problems'; \
	perl -pi -e 's/(If Carl has an out-of-town guest who asks him how to get to the restaurant, Carl could say:%)/\\par\n\1/' orcca.tex; \
	perl -p0i -e 's/^(\\begin{divisionexerciseegcol}\{\d+\}\{\}\{\}{p:exercise:KFJ}%\nLocate each point in the graph:%\n\\begin{sidebyside}\{1\})\{0\}\{0\}\{0\}%\n\\begin{sbspanel}\{1\}%\n/\1\{0.05\}\{0.05\}\{0\}%\n\\begin{sbspanel}\{0.9\}/m' orcca.tex; \
	perl -p0i -e 's/^(\\begin{divisionexerciseegcol}\{\d+\}\{\}\{\}{p:exercise:qMS}%\nLocate each point in the graph:%\n\\begin{sidebyside}\{1\})\{0\}\{0\}\{0\}%\n\\begin{sbspanel}\{1\}%\n/\1\{0.05\}\{0.05\}\{0\}%\n\\begin{sbspanel}\{0.9\}/m' orcca.tex; \
	perl -p0i -e 's/^(\\textbf{Domain and Range From a Graph}\\space\\space%\nA function is graphed.)(%\n\\begin{exercisegroupcol}\{3\}\n\\begin{divisionexerciseegcol}\{9\}\{\}\{\}{p:exercise:ruz}%)/\1 Find its domain and range\.\2/m' orcca.tex; \
	perl -p0i -e 's/^(\\begin{exercises-subsection}{Exercises}\{\}{Exercises}\{\}\{\}{p:exercises:iFU}\n.*?\n.*?\nA function is graphed\.)/\1 Find its domain and range\./m' orcca.tex; \
	perl -p0i -e 's/^(\\begin{divisionexerciseeg}\{\d+\}\{\}\{\}{p:exercise:fdz}%\n.*?\n\\begin{sidebyside})\{1\}\{0\}\{0\}\{0\}%\n\\begin{sbspanel}\{1\}%\n(\\includegraphics\[width=1\\linewidth\]{images\/webwork-.*?png}\n\\end{sbspanel}%\n)\\end{sidebyside}%\n\\begin{sidebyside}\{1\}\{0\}\{0\}\{0\}%\n\\begin{sbspanel}\{1\}%\n(\\includegraphics\[width=1\\linewidth\]{images\/webwork-.*?png}\n\\end{sbspanel}%\n\\end{sidebyside}%\n)/\1\{2\}\{0.12\}\{0.12\}\{0.12\}%\n\\begin{sbspanel}\{0.32\}%\n\2\\begin{sbspanel}\{0.32\}%\n\3/gm' orcca.tex; \
	perl -p0i -e 's/^(\\begin{divisionexerciseeg}\{\d+\}\{\}\{\}{p:exercise:LkI}%\n.*?\n\\begin{sidebyside})\{1\}\{0\}\{0\}\{0\}%\n\\begin{sbspanel}\{1\}%\n(\\includegraphics\[width=1\\linewidth\]{images\/webwork-.*?png}\n\\end{sbspanel}%\n)\\end{sidebyside}%\n\\begin{sidebyside}\{1\}\{0\}\{0\}\{0\}%\n\\begin{sbspanel}\{1\}%\n(\\includegraphics\[width=1\\linewidth\]{images\/webwork-.*?png}\n\\end{sbspanel}%\n\\end{sidebyside}%\n)/\1\{2\}\{0.12\}\{0.12\}\{0.12\}%\n\\begin{sbspanel}\{0.32\}%\n\2\\begin{sbspanel}\{0.32\}%\n\3/gm' orcca.tex; \
	perl -p0i -e 's/^(\\begin{divisionexerciseeg}\{\d+\}\{\}\{\}{p:exercise:rrR}%\n.*?\n\\begin{sidebyside})\{1\}\{0\}\{0\}\{0\}%\n\\begin{sbspanel}\{1\}%\n(\\includegraphics\[width=1\\linewidth\]{images\/webwork-.*?png}\n\\end{sbspanel}%\n)\\end{sidebyside}%\n\\begin{sidebyside}\{1\}\{0\}\{0\}\{0\}%\n\\begin{sbspanel}\{1\}%\n(\\includegraphics\[width=1\\linewidth\]{images\/webwork-.*?png}\n\\end{sbspanel}%\n\\end{sidebyside}%\n)/\1\{2\}\{0.12\}\{0.12\}\{0.12\}%\n\\begin{sbspanel}\{0.32\}%\n\2\\begin{sbspanel}\{0.32\}%\n\3/gm' orcca.tex; \
	perl -p0i -e 's/^(\\begin{divisionexerciseeg}\{\d+\}\{\}\{\}{p:exercise:Xza}%\n.*?\n\\begin{sidebyside})\{1\}\{0\.3\}\{0\.3\}\{0\}%\n\\begin{sbspanel}\{0\.4\}%\n(\\includegraphics\[width=1\\linewidth\]{images\/webwork-.*?png}\n\\end{sbspanel}%\n)\\end{sidebyside}%\n\\begin{sidebyside}\{1\}\{0\.3\}\{0\.3\}\{0\}%\n\\begin{sbspanel}\{0\.4\}%\n(\\includegraphics\[width=1\\linewidth\]{images\/webwork-.*?png}\n\\end{sbspanel}%\n\\end{sidebyside}%\n)/\1\{2\}\{0.12\}\{0.12\}\{0.12\}%\n\\begin{sbspanel}\{0.32\}%\n\2\\begin{sbspanel}\{0.32\}%\n\3/gm' orcca.tex; \
	perl -p0i -e 's/^(\\begin{divisionexerciseeg}\{\d+\}\{\}\{\}{p:exercise:lOV}%\n.*?\n\\begin{sidebyside})\{1\}\{0\}\{0\}\{0\}%\n\\begin{sbspanel}\{1\}%\n(\\includegraphics\[width=1\\linewidth\]{images\/webwork-.*?png}\n\\end{sbspanel}%\n)\\end{sidebyside}%\n\\begin{sidebyside}\{1\}\{0\}\{0\}\{0\}%\n\\begin{sbspanel}\{1\}%\n(\\includegraphics\[width=1\\linewidth\]{images\/webwork-.*?png}\n\\end{sbspanel}%\n\\end{sidebyside}%\n)/\1\{2\}\{0.12\}\{0.12\}\{0.12\}%\n\\begin{sbspanel}\{0.32\}%\n\2\\begin{sbspanel}\{0.32\}%\n\3/gm' orcca.tex; \
	perl -p0i -e 's/^(\\begin{divisionexerciseeg}\{\d+\}\{\}\{\}{p:exercise:RWe}%\n.*?\n\\begin{sidebyside})\{1\}\{0\}\{0\}\{0\}%\n\\begin{sbspanel}\{1\}%\n(\\includegraphics\[width=1\\linewidth\]{images\/webwork-.*?png}\n\\end{sbspanel}%\n)\\end{sidebyside}%\n\\begin{sidebyside}\{1\}\{0\}\{0\}\{0\}%\n\\begin{sbspanel}\{1\}%\n(\\includegraphics\[width=1\\linewidth\]{images\/webwork-.*?png}\n\\end{sbspanel}%\n\\end{sidebyside}%\n)/\1\{2\}\{0.12\}\{0.12\}\{0.12\}%\n\\begin{sbspanel}\{0.32\}%\n\2\\begin{sbspanel}\{0.32\}%\n\3/gm' orcca.tex; \
	perl -p0i -e 's/^(A function is graphed.)(%\n\\begin{exercisegroupcol}\{3\}\n\\begin{divisionexerciseegcol}\{21\}\{\}\{\}{p:exercise:gTd}%)/\1 Find its domain.\2/m' orcca.tex; \
	echo 'INDIVIDUAL PAGE BREAKS'; \
	echo 'CHAPTER 1'; \
	echo 'SECTION 1.1'; \
	perl -p0i -e 's/^(.*:UqM.*?\n(.*?\n)*?)(\\noindent\\textbf{Explanation})/\1\\newpage%\n\3/m' orcca.tex; \
	perl -pi -e 's/(^\\begin{exercises-subsection}.*?:hKx)/\\newpage%\n\1/' orcca.tex; \
	echo 'SECTION 1.2'; \
	perl -pi -e 's/(\\begin{example}\{\}{x:example:example-combining-like-terms}%)/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/(\\begin{example}\{\}{p:example:XHm}%)/\\newpage%\n\1/' orcca.tex; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?\n.*?exercise:xZj)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	echo 'SECTION 1.3'; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?:xbu)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	perl -p0i -e 's/^(\\hrulefill\\\\%\n.*?\n.*?\n.*?:DAA}%)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	echo 'SECTION 1.4'; \
	perl -pi -e 's/(The following are some linear equations in one variable:%)/\\newpage%\n\1/' orcca.tex; \
	perl -p0i -e 's/^(\\begin{inlineexercise}\{\}{p:exercise:yin}%\n(.*?\n)*?)(\\noindent\\textbf{Explanation})/\1\\newpage%\n\2/m' orcca.tex; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?:nJi)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	echo 'SECTION 1.5'; \
	perl -pi -e 's/(^\\begin\{example\}\{\}\{x:example:example-one-step-equation-fraction-type-one\}%)/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/(\\begin{example}\{\}{p:example:CyD}%)/\\newpage%\n\1/' orcca.tex; \
	echo 'SECTION 1.7'; \
	perl -pi -e 's/(\\begin{inlineexercise}\{\}{p:exercise:mST}%)/\\newpage%\n\1/' orcca.tex; \
	echo 'SECTION 1.8'; \
	echo 'CHAPTER 2'; \
	echo 'SECTION 2.1'; \
	perl -pi -e 's/(\\begin{inlineexercise}\{\}{p:exercise:ggs}%)/\\newpage%\n\1/' orcca.tex; \
	perl -p0i -e 's/^(Here we revisit \\hyperref\[x:example:example-savings-pattern\]{Example~\\ref{x:example:example-savings-pattern\}\}\.%\n\\par\nA savings account starts with \\\(\\\$500\\\)\. Each month, an automatic deposit of \\\(\\\$150\\\) is made. Find the number of months it will take for the balance to reach \\\(\\\$1\{,\}700\\\)\.%\n\\par\\smallskip%\n)/\1\\newpage%\n/m' orcca.tex; \
	perl -pi -e 's/^(\\noindent Here is a summary collection of the distinctions that you should understand between simplifying expressions, evaluating expressions and solving equations.%)/\1\n\\newpage%/' orcca.tex; \
	perl -p0i -e 's/^(A savings account starts with \\\(\\\$500\\\)\. Each month, an automatic deposit of \\\(\\\$150\\\) is made\. Find.*?\n\\par\\smallskip%\n)/\1\\newpage%\n/m' orcca.tex; \
	echo 'SECTION 2.2'; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?exercise:JOH)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	echo 'SECTION 2.3'; \
	perl -pi -e 's/(\\noindent\\textbf{Explanation}.*Assume Bao)/\\newpage%\n\1/' orcca.tex; \
	echo 'SECTION 2.4'; \
	perl -p0i -e 's/(\\begin{namedlist}\n\\captionof{namedlistcap}{Special Solution Sets for Equations and Inequalities\\label{x:list:list-special-solution-sets}})/\\newpage%\n\1/' orcca.tex; \
	echo 'SECTION 2.5'; \
	perl -p0i -e 's/^(\\begin{example}\{\}{x:example:example-solve-for-variable-slope-intercept}%)/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/^(\\noindent\\textbf{Explanation}\.\\hypertarget{p:solution:Xlj})/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/^(\\begin{inlineexercise}\{\}{x:exercise:exercise-solve-for-variable-standard-form}%)/\\newpage%\n\1/' orcca.tex; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?\n.*?\n.*?\n.*?exercises:dvU)/\\newpage%\n\1/m' orcca.tex; \
	echo 'CHAPTER 3'; \
	echo 'SECTION 3.1'; \
	perl -p0i -e 's/^(\\begin{reading-questions-subsection-numberless}{Reading Questions}\{\}{Reading Questions}\{\}\{\}{.*?}\n\\begin{divisionexercise}\{1\}\{\}\{\}{.*?}%\nWhat are the coordinates of the gas station in the map of Carl.s neighborhood\?%)/\\newpage%\n\1/m' orcca.tex; \
	echo 'SECTION 3.2'; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?\n.*?exercise:RHS)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	echo 'SECTION 3.3'; \
	perl -pi -e 's/^(\\begin{inlineexercise}\{\}{p:exercise:EYb}%)/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/^(\\begin{inlineexercise}\{\}{p:exercise:bQC}%)/\\newpage%\n\1/' orcca.tex; \
	echo 'SECTION 3.4'; \
	perl -pi -e 's/(.*?example:uFj)/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/(.*?exercise:XRM)/\\newpage%\n\1/' orcca.tex; \
	echo 'SECTION 3.5'; \
	perl -pi -e 's/(.*?example:gBr)/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/^(\\noindent\\textbf{Explanation}\.\\hypertarget{.*?}\{\}\quad\{\}Do your best to identify two points on the line. We go with \\\(\(0,27500\)\\\) and \\\(\(11000,45000\)\\text\{\.\}\\\)%)/\\newpage%\n\1/' orcca.tex; \
	echo 'SECTION 3.6'; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?exercise:WRk)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?\n.*?exercise:Ohs)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	echo 'SECTION 3.7'; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?exercise:zcU)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	perl -pi -e 's/^(.*?p:exercises:PMK})/\\newpage%\n\1/' orcca.tex; \
	echo 'SECTION 3.8'; \
	perl -pi -e 's/(.*?example:sSa)/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/^(\\noindent\\textbf{Explanation}\.\\hypertarget{.*?}\{\}\\quad\{\}First, we will find Line \\\(A\\\).s slope by rewriting its equation from standard form to slope-intercept form:%)/\\newpage%\n\1/' orcca.tex; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?\n.*?exercise:PjY)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	echo 'SECTION 3.10'; \
	perl -pi -e 's/^(\\noindent\\textbf{Explanation}\.\\hypertarget{p:solution:OrR}\{\}\\quad\{\}\\leavevmode%)/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/^(\\noindent\\textbf{Explanation}\.\\hypertarget{p:solution:aGj}\{\}\\quad\{\}\\leavevmode%)/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/^(\\noindent\\textbf{Explanation}\.\\hypertarget{p:solution:GNs}\{\}\\quad\{\}\\leavevmode%)/\\newpage%\n\1/' orcca.tex; \
	echo 'CHAPTER 4'; \
	echo 'SECTION 4.1'; \
	perl -p0i -e 's/(\\begin{namedlist}\n\\captionof{namedlistcap}{A summary of the three types of systems of equations and their solution sets\.\\label{x:list:list-summary-of-types-of-systems}})/\\newpage%\n\1/' orcca.tex; \
	perl -p0i -e 's/^(.*?\n.*?exercise:ysn)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	echo 'SECTION 4.2'; \
	perl -pi -e 's/(.*?exercise:lJw)/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/(.*?example:ULl)/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/^(\\noindent\\textbf{Explanation}\.\\hypertarget{.*?}\{\}\\quad\{\}If an equation involves fractions, it is helpful to clear denominators by multiplying both sides of the equation by a common multiple of the denominators.%)/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/^(Lastly, we can determine the value of \\\(v\\\) by using the earlier equation where we isolated \\\(v\\\):%)/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/^(And then substitute \\\(s\\\) in the second equation with \\\(600-v\\\):%)/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/^(\\noindent\\textbf{Explanation}\.\\hypertarget{p:solution:qHK)/\\newpage%\n\1/' orcca.tex; \
	echo 'SECTION 4.3'; \
	perl -pi -e 's/(To check our work, substitute \\\(A=560\\\) and \\\(B=440\\\) into the original equations:%)/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/^(To solve for \\\(y\\\), we can substitute \\\(2\\\) for \\\(x\\\) into either of the original equations or the new one\. We use the first original equation, \\\(3x-4y=2\\\):%)/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/^(\\noindent To summarize, if a variable is already isolated or has a coefficient of \\\(1\\\), consider using the substitution method\. If both equations are in standard form or none of the coefficients are equal to \\\(1\\\), we suggest using the elimination method\. Either way, if you have fraction or decimal coefficients, it may help to scale your equations so that only integer coefficients remain.%)/\\newpage%\n\1/' orcca.tex; \
	echo 'SECTION 5.1'; \
	perl -p0i -e 's/^(\\hrulefill\\\\%\n.*?\n.*?\n.*?p:exercise:bzu)/\\newpage%\n\\noindent\1/m' orcca.tex; \
	echo 'SECTION 5.2'; \
	perl -p0i -e 's/^(\\begin{namedlist}\n\\captionof{namedlistcap}{Summary of the Rules of Exponents for Multiplication\\label{x:list:list-rules-of-exponents}})/\\newpage%\n\1/m' orcca.tex; \
	echo 'SECTION 5.3'; \
	perl -p0i -e 's/^(\\begin{namedlist}\n\\captionof{namedlistcap}{Summary of the Rules of Exponents \(Thus Far\)\\label{x:list:list-rules-of-exponents-four-rules}})/\\newpage%\n\1/m' orcca.tex; \
	perl -p0i -e 's/^(where \\\(m\\\) is the object.s mass, and \\\(V\\\) is its volume\. The mass of a certain cancerous growth can be modeled by \\\(4t\^3-6t\^2\+8t\\\) grams, where \\\(t\\\) is the number of days since the growth began\. If its volume is \\\(2t\\\) cubic centimeters, find the growth.s density\.%\n\\par\\smallskip%\n)/\1\\newpage%\n/m' orcca.tex; \
	echo 'SECTION 5.4'; \
	perl -pi -e 's/^(To finish multiplying, we.ll continue by distributing again, but this time across \\\(\(x+3\)\\\):%)/\\newpage%\n\1/' orcca.tex; \
	echo 'SECTION 5.5'; \
	perl -p0i -e 's/^(\\begin{inlineexercise}.*?\nExpand \\\(\(2y-6\)\^3\\text\{\.\}\\\)%)/\\newpage%\n\1/m' orcca.tex; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?\n.*?exercise:goW)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	echo 'SECTION 5.7'; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?\n.*?exercise:snB)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?\n.*?exercise:vSb)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	echo 'SECTION 6.1'; \
	perl -p0i -e 's/^(\\begin{inlineexercise}\{\}{p:exercise:ALy}%\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n\\end{multicols}\n)/\1\\newpage%\n/m' orcca.tex; \
	echo 'SECTION 6.3'; \
	perl -pi -e 's/^(\\begin{remark}\{\}{x:remark:remark-two-representations-of-rational-exponents}%)/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/^(\\begin{example}\{\}{p:example:SaN}%)/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/^(\\begin{subsectionptx}{More Expressions with Rational Exponents}\{\}{More Expressions with Rational Exponents}\{\}\{\}{p:subsection:QlA})/\\newpage%\n\1/' orcca.tex; \
	echo 'SECTION 6.4'; \
	perl -pi -e 's/^(\\noindent\\textbf{Explanation}\.\\hypertarget{p:solution:KkT)/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/^(\\begin{divisionexerciseegcol}\{50\}\{\}\{\}{p:exercise:vMx}%)/\\newpage%\n\1/' orcca.tex; \
	perl -p0i -e 's/^(\\textbf{Solving Radical Equations with Variables}.*?\n.*?\n.*?p:exercise:DLN)/\\newpage%\n\1/m' orcca.tex; \
	echo 'SECTION 6.5'; \
	perl -pi -e 's/^(\\begin{example}{More Expressions with Rational Exponents\.}{p:example:XFm}%)/\\newpage%\n\1/' orcca.tex; \
	echo 'SECTION 7.1'; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?exercise:Yhh)/\\newpage%\n\1/m' orcca.tex; \
	echo 'SECTION 8.3'; \
	perl -pi -e 's/^(\\begin{subsectionptx}{Summary}\{\}{Summary}\{\}\{\}{x:subsection:subsection-list-of-geometry-formulas})/\\newpage%\n\1/' orcca.tex; \
	echo 'SECTION 8.3'; \
	perl -p0i -e 's/^(\\hrulefill\\\\%\n.*?\n.*?\n\\begin{divisionexerciseegcol}\{29\}\{\}\{\}{p:exercise:rSy}%)/\\newpage%\n\\noindent\1/m' orcca.tex; \
	echo 'SECTION 8.5'; \
	perl -p0i -e 's/^(\\begin{exercises-subsection}.*?\n.*?\n.*?\n.*?\n\\begin{divisionexerciseegcol}\{1\}\{\}\{\}{p:exercise:WFP}%)/\\newpage%\n\1/m' orcca.tex; \
	echo 'SECTION 9.1'; \
	perl -p0i -e 's/^(\\textbf{Tables for Equations}.*?\nMake a table for the equation.%\n\\begin{exercisegroupcol}\{2\}\n\\begin{divisionexerciseegcol}\{5\}\{\}\{\}{g:exercise:)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	echo 'SECTION 9.2'; \
	perl -pi -e 's/^(\\begin{example}{}{p:example:olh}%)/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/^(.*?p:solution:TBs)/\\newpage%\n\1/' orcca.tex; \
	perl -p0i -e 's/^(\\textbf{Algebraically Determining the Vertex and Axis of Symmetry of Quadratic Functions}\\space\\space%\nFind the axis of symmetry and vertex of the quadratic )function.%/\\newpage%\n\\noindent \1equation\.%/m' orcca.tex; \
	echo 'SECTION 9.3'; \
	perl -pi -e 's/^(\\item\{\}To determine the horizontal intercepts, we.ll solve \\\(H=0\\\)\.%)/\\newpage%\n\1/' orcca.tex; \
	echo 'SECTION 9.4'; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?\n.*?\n.*?This region is highlighted in \\hyperref\[x:figure:figure-parabola-line-inequality\])/\\newpage%\n\1/m' orcca.tex; \
	echo 'SECTION 10.7'; \
	echo 'SECTION 10.8'; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?\n.*?exercise:KMR)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	echo 'SECTION 12.3'; \
	perl -pi -e 's/^(\\begin{divisionexerciseeg}\{98\}\{\}\{\}{p:exercise:AuZ}%)/\\newpage%\n\1/' orcca.tex; \
	echo 'SECTION 12.1'; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?p:exercise:zbl)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	echo 'SECTION 12.2'; \
	perl -pi -e 's/^(\\begin{exercises-subsection}{Exercises}\{\}{Exercises}\{\}\{\}{p:exercises:maM})/\\newpage%\n\1/' orcca.tex; \
	echo 'SECTION 12.5'; \
	perl -pi -e 's/^(\\noindent\\textbf{Explanation}\.\\hypertarget{p:solution:ECt})/\\newpage%\n\1/' orcca.tex; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?exercise:oJB)/\\newpage%\n\1/m' orcca.tex; \
	perl -pi -e 's/^(\\begin{divisionexerciseeg}\{19\}\{\}\{\}{p:exercise:lOV}%)/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/^(.*?solution:jlT)/\\newpage%\n\1/' orcca.tex; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?p:exercise:fdz}%)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?p:exercise:ciT}%)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	echo 'SECTION 12.2'; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?\n.*?p:exercise:SJh)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	echo 'SECTION 12.5'; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?p:exercise:NIp)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	echo 'SECTION 13.4'; \
	perl -pi -e 's/^(\\noindent\\textbf{Explanation}\.\\hypertarget{p:solution:CCY)/\\newpage%\n\1/' orcca.tex; \
	echo 'SECTION 13.6'; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?\n.*?exercise:TME)/\\newpage%\n\\noindent\1/m' orcca.tex; \
	echo 'SECTION 13.1'; \
	perl -pi -e 's/^(\\noindent.*solution:izz)/\\newpage%\n\1/' orcca.tex; \
	perl -p0i -e 's/^(\\begin{example}\{\}{g:example:.*?}%\nFind the slope and vertical intercept of \\\(y=h\(x\)\\\), where \\\(h\(x\)=\\frac\{5\}\{3\}x-4\\\)\.)/\\newpage%\n\1/m' orcca.tex; \
	perl -p0i -e 's/^(\\begin{inlineexercise}.*?\nFind the \\\(y\\\)-intercept and \\\(x\\\)-intercept of the line given by the equation\. If a particular intercept does not exist, enter \\mono{none} into all the answer blanks for that row\.%\n%\n\\begin{equation\*}\n2 x + 5 y = -20)/\\newpage%\n\1/m' orcca.tex; \
	echo 'SECTION 13.2'; \
	perl -p0i -e 's/^(\\hrulefill.*?\n.*?\n.*?\n.*?p:exercise:YvT}%)/\\newpage%\n\\noindent\1/m' orcca.tex; \
	perl -pi -e 's/^(\\noindent Let.s look at another graph\. Let \\\(h\(x\)=-x\^2\\\) and let \\\(j\(x\)=-\(x+3\)\^2+4\\\)\.%)/\\newpage%\n\1/' orcca.tex; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?exercise:zjp)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?\n.*?exercise:tud)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	echo 'SECTION 13.4'; \
	perl -pi -e 's/^(\\noindent\\textbf{Explanation}\.\\hypertarget{p:solution:wSm})/\\newpage%\n\1/' orcca.tex; \
	echo 'SECTION 13.5'; \
	perl -pi -e 's/^(\\noindent.*?solution:zIF)/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/^(\\begin{exercises-subsection}{Exercises}\{\}{Exercises}\{\}\{\}{p:exercises:fBt})/\\newpage%\n\1/' orcca.tex; \
	echo 'SECTION 13.5'; \
	perl -p0i -e 's/^(\\noindent\\textbf{Explanation}\.\\hypertarget{g.*?\n.*?\n.*?\nThe specifics of how to use any one particular technology)/\\newpage%\n\1/m' orcca.tex; \
	echo 'SECTION 13.7'; \
	perl -p0i -e 's/^(\\noindent Let.s turn to an example involving a linear equation.%\n\\begin{example}.*?\nSolve the inequality \\\(3x-2\\lt7\\\) graphically\.%)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	perl -p0i -e 's/^(\\begin{example}.*?\nTo graphically solve the inequality \\\(\\abs{x-1} \\gt 3\\\) would mean looking for the \\\(x\\\)-values where the graph of \\\(y=\\abs{x-1}\\\) is \\emph{above} the line \\\(y=3\\\)\.%)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	perl -pi -e 's/^(\\noindent Solving inequalities with quadratic expressions graphically is very similar to solving absolute value inequalities graphically.%)/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/^(\\item\{\}To now solve \\\(42\(x-2\)\^2-60 \\lt 21x-39\\\),)/\\newpage%\n\1/' orcca.tex; \
	perl -p0i -e 's/^(\\noindent\\textbf{Explanation}.*?\n\\begin{sidebyside}.*?\n\\begin{sbspanel}\{0.47\}%\nTo solve the inequality \\\(2\\le f\(x\) \\lt 6\\\))/\\newpage%\n\1/m' orcca.tex; \
	echo 'SECTION 13.8'; \
	perl -p0i -e 's/^(\\begin{example}{Graphing Lines Using Intercepts.}.*?\nUse the intercepts of \\\(4x-2y=16\\\) to graph the equation\.%)/\\newpage%\n\1/m' orcca.tex; \
	perl -p0i -e 's/^(\\item\{\}\\leavevmode%\n\\begin{sidebyside}.*?\n\\begin{sbspanel}{0\.47}%\nThe solutions are all \\\(x\\\)-values where)/\\newpage%\n\1/m' orcca.tex; \
	echo 'APPENDIX'; \
	perl -p0i -e 's/^(\\begin{inlineexercise[^\n]*?:VDr}%\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n.*?\n)/\1\\newpage%\n/m' orcca.tex; \
	perl -p0i -e 's/^(\\begin{inlineexercise.*exercise:LKP}%\n.*?\n.*?\n)/\1\\newpage%\n/m' orcca.tex; \
	perl -pi -e 's/(\\begin{divisionexerciseeg}{\d+}{}{}{p:exercise:zKS}%)/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/^(\\begin{inlineexercise}\{\}{p:exercise:FpW}%)/\\newpage%\n\1/' orcca.tex; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?exercise:CJL}%)/\\newpage%\n\1/m' orcca.tex; \
	perl -p0i -e 's/^(.*?\n.*?\n.*?\n.*?exercise:FNi}%)/\\newpage%\n\\noindent \1/m' orcca.tex; \
	perl -p0i -e 's/^(\\begin{sidebyside}.*?\n.*?\n.*?\n.*?\n.*?\n{Units of Area)/\\newpage%\n\\noindent\1/m' orcca.tex; \
	echo 'INDIVIDUAL CUTTING'; \
	echo 'SECTION 1.3'; \
	perl -pi -e 's/^In .*? notation: +\\fillin{\d+}%\n//g' orcca.tex; \
	echo 'SECTION 1.6'; \
	perl -p0i -e 's/\\par\nIn .*? notation, the solution set is +\\fillin{\d+}\.%\n//g' orcca.tex; \
	echo 'SECTION 2.2'; \
	perl -pi -e 's/^ *\\fillin\{10\}  \\fillin\{2\}  \\fillin\{10\}%//g' orcca.tex; \
	echo 'SECTION 3.6'; \
	perl -pi -e 's/^An equation for this line in.*\\fillin{\d+}\.%\n//g' orcca.tex; \
	perl -pi -e 's/^In slope-intercept form:  \\fillin\{20\}%\n//g' orcca.tex; \
	echo 'SECTION 9.1'; \
	perl -p0i -e 's/^(Axis of symmetry:  \\fillin{\d+}%\n\\par\nVertex:  \\fillin{\d+}%\n)//gm' orcca.tex; \
	echo 'SECTION 9.2'; \
	perl -p0i -e 's/^(\\\(y\\\)-intercept:  \\fillin{\d+}%\n\\par\n\\\(x\\\)-intercept\(s\):  \\fillin{\d+}%\n)//gm' orcca.tex; \
	echo 'SECTION 9.3'; \
	perl -pi -e 's/^(\\noindent If we are solving graphically and something is already providing you with the graph, it.s not even necessary to have math expressions for the two curves\.%)/\\newpage%\n\1/' orcca.tex; \
	perl -pi -e 's/^(\\noindent Occasionally, a curve abruptly ..stops.., and we need to recognize this in a solution to an inequality\.%)/\\newpage%\n\1/' orcca.tex; \
	echo 'SECTION 12.1'; \
	perl -pi -e 's/^Interpretation:%$/%/g' orcca.tex; \
	echo 'SECTION 12.2'; \
	perl -p0i -e 's/\\par\n\\noindent In .*? notation: +\\fillin{\d+}%\n//g' orcca.tex; \
	perl -p0i -e 's/^((This|The) function has domain  \\fillin\{\d+\} and range  \\fillin\{\d+\}\.%\n)//gm' orcca.tex; \
	echo 'SECTION 13.1'; \
	perl -p0i -e 's/^What is its domain\?%\n//gm' orcca.tex; \
	perl -p0i -e 's/^(The domain of \\\(.\\\) is  \\fillin{\d+}%\n\\par\nThe range of \\\(.\\\) is  \\fillin{\d+}%\n)//gm' orcca.tex; \
	echo 'REMOVE ALL ANSWER BLANKS AND EQUALS SIGNS THAT ARE IN SHORT LINES LIKE 1+2=___ '; \
	perl -p0i -e 's/^(\\\(((?!(\\\)|text)).)*) *=([ \n}]*\\\)) *\\fillin{\d+} *\.?%\n/\1\4%\n/gm' orcca.tex; \
	perl -pi -e 's/^(\\item\{\}\\\(((?!(\\\)|text)).)*) *=([ }]*\\\)) *\\fillin{\d+} *\.?%\n/\1\4%\n/g' orcca.tex; \
	perl -pi -e 's/^(\\\(((?!(\\\)|text)).)*\\\)) *= *\\fillin{\d+} *\.?%\n/\1%\n/g' orcca.tex; \
	perl -pi -e 's/^(\\item\{\}\\\(((?!(\\\)|text)).)*\\\)) *= *\\fillin{\d+} *\.?%\n/\1%\n/g' orcca.tex; \
	perl -pi -e 's/^(\\\(((?!(\\\)|text)).)*) *=\{\}([ }]*\\\)) *\\fillin\{\d+\} *\.?%\n/\1\4%\n/g' orcca.tex; \
	perl -pi -e 's/^(\\\(((?!(\\\)|text)).)*) *\\approx([ }]*\\\)) *\\fillin{\d+} *\.?%\n/\1\4%\n/g' orcca.tex; \
	perl -p0i -e 's/^(\\\(((?!(\\\)|text)).)*) *\\approx([ \n}]*\\\)) *\\fillin{\d+} *\.?%\n/\1\4%\n/gm' orcca.tex; \
	perl -pi -e 's/^(\\item\{\}\\\(((?!(\\\)|text)).)*) *\\approx([ }]*\\\)) *\\fillin{\d+} *\.?%\n/\1\4%\n/g' orcca.tex; \
	perl -pi -e 's/^(\\\(((?!(\\\)|text)).)*\\\)) *\\approx *\\fillin{\d+} *\.?%\n/\1%\n/g' orcca.tex; \
	perl -pi -e 's/^(\\item\{\}\\\(((?!(\\\)|text)).)*\\\)) *\\approx *\\fillin{\d+} *\.?%\n/\1%\n/g' orcca.tex; \
	perl -pi -e 's/^(\\\(((?!(\\\)|text)).)*) *\\approx\{\}([ }]*\\\)) *\\fillin\{\d+\} *\.?%\n/\1\4%\n/g' orcca.tex; \
	perl -p0i -e 's/^\\\(x\\\)%\n/%\n/gm' orcca.tex; \
	echo 'EDGE INDEXING AND PAGE RENUMBERING'; \
	perl -pi -e 's/^(\\begin{partptx}{Linear Equations and Lines})/\\xpatchcmd{\\part}{\\thispagestyle{plain}}{\\begin{tikzpicture}\[remember picture,overlay\]\\draw \[color=emerald, fill=emerald\] \(\[xshift=-0.625in\]current page\.north east\) rectangle \(current page\.south east\);\\end{tikzpicture}\\break\\pagenumbering{arabic}\\thispagestyle{plain}}\{\}\{\}\\xpatchcmd{\\\@endpart}{\\vfil\\newpage}{\\vfil\\newpage}\{\}\{\}\n\1/' orcca.tex; \
	perl -pi -e 's/^(\\begin{partptx}{Preparation for STEM})/\\xpatchcmd{\\part}{\\thispagestyle{plain}}{\\begin{tikzpicture}\[remember picture,overlay\]\\draw \[color=turquoise, fill=turquoise\] \(\[xshift=-0.625in\]current page\.north east\) rectangle \(current page\.south east\);\\end{tikzpicture}\\break\\pagenumbering{arabic}\\thispagestyle{plain}}\{\}\{\}\\xpatchcmd{\\\@endpart}{\\vfil\\newpage}{\\vfil\\newpage}\{\}\{\}\n\1/' orcca.tex; \
	perl -pi -e 's/^(\\begin{partptx}{Preparation for College Algebra})/\\xpatchcmd{\\part}{\\thispagestyle{plain}}{\\begin{tikzpicture}\[remember picture,overlay\]\\draw \[color=amethyst, fill=amethyst\] \(\[xshift=-0.625in\]current page\.north east\) rectangle \(current page\.south east\);\\end{tikzpicture}\\break\\pagenumbering{arabic}\\thispagestyle{plain}}\{\}\{\}\\xpatchcmd{\\\@endpart}{\\vfil\\newpage}{\\vfil\\newpage}\{\}\{\}\n\1/' orcca.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=emerald,   fill=emerald  ] ([xshift=-0.625in] \$$ \(current page.north east\) \$$ ) rectangle ( \$$  \(A\)!1\/13!\(B\)          \$$ );\\end{tikzpicture}\n/m' orcca.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=emerald,   fill=emerald  ] ([xshift=-0.625in] \$$  \(A\)!2\/13-1\/13!\(B\)    \$$ ) rectangle ( \$$  \(A\)!2\/13!\(B\)          \$$ );\\end{tikzpicture}\n/m' orcca.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=emerald,   fill=emerald  ] ([xshift=-0.625in] \$$  \(A\)!3\/13-1\/13!\(B\)    \$$ ) rectangle ( \$$  \(A\)!3\/13!\(B\)          \$$ );\\end{tikzpicture}\n/m' orcca.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=emerald,   fill=emerald  ] ([xshift=-0.625in] \$$  \(A\)!4\/13-1\/13!\(B\)    \$$ ) rectangle ( \$$  \(A\)!4\/13!\(B\)          \$$ );\\end{tikzpicture}\n/m' orcca.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=turquoise, fill=turquoise] ([xshift=-0.625in] \$$  \(A\)!5\/13-1\/13!\(B\)    \$$ ) rectangle ( \$$  \(A\)!5\/13!\(B\)          \$$ );\\end{tikzpicture}\n/m' orcca.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=turquoise, fill=turquoise] ([xshift=-0.625in] \$$  \(A\)!6\/13-1\/13!\(B\)    \$$ ) rectangle ( \$$  \(A\)!6\/13!\(B\)          \$$ );\\end{tikzpicture}\n/m' orcca.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=turquoise, fill=turquoise] ([xshift=-0.625in] \$$  \(A\)!7\/13-1\/13!\(B\)    \$$ ) rectangle ( \$$  \(A\)!7\/13!\(B\)          \$$ );\\end{tikzpicture}\n/m' orcca.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=turquoise, fill=turquoise] ([xshift=-0.625in] \$$  \(A\)!8\/13-1\/13!\(B\)    \$$ ) rectangle ( \$$  \(A\)!8\/13!\(B\)          \$$ );\\end{tikzpicture}\n/m' orcca.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=turquoise, fill=turquoise] ([xshift=-0.625in] \$$  \(A\)!9\/13-1\/13!\(B\)    \$$ ) rectangle ( \$$  \(A\)!9\/13!\(B\)          \$$ );\\end{tikzpicture}\n/m' orcca.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=amethyst,  fill=amethyst ] ([xshift=-0.625in] \$$ \(A\)!10\/13-1\/13!\(B\)    \$$ ) rectangle ( \$$ \(A\)!10\/13!\(B\)          \$$ );\\end{tikzpicture}\n/m' orcca.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=amethyst,  fill=amethyst ] ([xshift=-0.625in] \$$ \(A\)!11\/13-1\/13!\(B\)    \$$ ) rectangle ( \$$ \(A\)!11\/13!\(B\)          \$$ );\\end{tikzpicture}\n/m' orcca.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=amethyst,  fill=amethyst ] ([xshift=-0.625in] \$$ \(A\)!12\/13-1\/13!\(B\)    \$$ ) rectangle ( \$$ \(A\)!12\/13!\(B\)          \$$ );\\end{tikzpicture}\n/m' orcca.tex; \
	perl -p0i -e 's/^(\\begin{chapterptx}.*?{x:chapter:[^}]*?})\n/\1\\begin\{tikzpicture\}[remember picture,overlay]\\node \(A\) at ( \$$ (current page.north east) - (0,0.125) \$$ ) \{\}; \\node \(B\) at ( \$$ (current page.south east) + (0,0.125) \$$ ) \{\}; \\draw [color=amethyst,  fill=amethyst ] ([xshift=-0.625in] \$$ \(A\)!13\/13-1\/13!\(B\)    \$$ ) rectangle ( \$$ \(current page.south east\) \$$ );\\end{tikzpicture}\n/m' orcca.tex; \
	perl -pi -e 's/^(\\begin{appendixptx}.*?\n)/\\cleardoublepage\n\\pagenumbering{arabic}\n\\renewcommand{\\thepage}{\\thechapter\\arabic{page}}\n\1\\begin{tikzpicture}\[remember picture,overlay\]\\draw \[color=ruby, fill=ruby\] \(\[xshift=-0.625in\]current page.north east\) rectangle \(current page\.south east\);\\end{tikzpicture}\n/g' orcca.tex; \
	xelatex orcca.tex; \
	xelatex orcca.tex; \
	xelatex orcca.tex; \
#	perl -p0i -e 's/(\\textbf{.*?}\\space\\space%\n\\begin\{exercisegroup.*?\n(.*?\n)*?\\end\{divisionexerciseeg.*?\n)((.*?\n)*?\\end\{exercisegroup.*?\n)/\\makeatletter\\\@beginparpenalty=10000\\makeatother\n\1\\makeatletter\\\@beginparpenalty=-51\\makeatother\n\3\\makeatletter\\\@beginparpenalty=-51\\makeatother\n/g' orcca.tex; \
	echo 'SHORTEN UNRESOLVED XREF WARNINGS'; \
	perl -pi -e 's/\{\(\(\(Unresolved xref, reference "[\w\-]*"; check spelling or use "provisional" attribute\)\)\)\}\\hyperlink\{\}\{(\w*?)~\}/\1 A.B/g' orcca.tex; \
	perl -pi -e 's/\{\(\(\(Unresolved xref, reference "[\w\-]*"; check spelling or use "provisional" attribute\)\)\)\}(\w*?)~/\1 A.B/g' orcca.tex; \
	perl -pi -e 's/\{\(\(\(Unresolved xref, reference "[\w\-]*"; check spelling or use "provisional" attribute\)\)\)\}\\hyperlink\{\}{(.*?)}/\1/g' orcca.tex; \


#  HTML output
#  Output lands in the subdirectory:  $(HTMLOUT)
html:
	date
	install -d $(OUTPUT)
	-rm -r $(HTMLOUT) || :
	install -d $(HTMLOUT)
	install -d $(HTMLOUT)/images
	install -d $(IMGOUT)
	install -d $(IMGSRC)
	cp -a $(IMGOUT) $(HTMLOUT) || :
	cp -a $(IMGSRC) $(HTMLOUT) || :
	cp -a $(WWOUT)/*.png $(HTMLOUT)/images || :
	cp -a $(SRC)/favicon $(HTMLOUT) || :
	cp -r $(CSS) $(HTMLOUT) || :
	cd $(HTMLOUT); \
	xsltproc --xinclude --stringparam publisher $(PUBFILE) --stringparam exercise.inline.hint no --stringparam exercise.inline.answer no --stringparam exercise.inline.solution yes --stringparam exercise.divisional.hint no --stringparam exercise.divisional.answer no --stringparam exercise.divisional.solution no --stringparam html.knowl.exercise.inline no --stringparam html.knowl.example no --stringparam html.css.extra 'css/orcca.css' --stringparam webwork.divisional.static no $(XSL)/orcca-html.xsl $(MAINFILE); \
	perl -pi -e 's/(\\require{cancel})/\1\\require{color}/' *.html; \
	perl -pi -e 's/(\\require{cancel})/\1\\require{color}/' knowl/*.html; \
	perl -pi -e 's/https:\/\/pretextbook\.org\/css\/[\d\.]*\/colors_default\.css/css\/colors_sapphire_gray.css/' index.html orcca.html frontmatter.html colophon-1.html acknowledgement-1.html preface-to-all.html preface-pedagogical-decisions.html preface-entering-webwork-answers.html; \
	perl -pi -e 's/https:\/\/pretextbook\.org\/css\/[\d\.]*\/colors_default\.css/css\/colors_sapphire_emerald.css/' part-linear-equations-and-lines.html chapter-variables-expressions-and-equations.html section-variables-and-evaluating-expressions.html section-combining-like-terms.html section-comparison-symbols-and-notation-for-intervals.html section-equations-and-inequalities-as-true-false-statements.html section-solving-one-step-equations.html section-solving-one-step-inequalities.html section-algebraic-properties-and-simplifying-expressions.html section-modeling-with-equations-and-inequalities.html review-variables-expressions-and-equations.html chapter-linear-equations-and-inequalities.html section-solving-multistep-linear-equations.html section-solving-multistep-linear-inequalities.html section-linear-equations-and-inequalities-with-fractions.html section-special-solution-sets.html section-isolating-a-linear-variable.html review-linear-equations-and-inequalities.html chapter-graphing-lines.html section-cartesian-coordinates.html section-graphing-equations.html section-exploring-two-variable-data-and-rate-of-change.html section-slope.html section-slope-intercept-form.html section-point-slope-form.html section-standard-form.html section-horizontal-vertical-parallel-and-perpendicular-lines.html section-summary-of-graphing-lines.html review-graphing-lines.html chapter-systems-of-linear-equations.html section-solving-systems-of-linear-equations-by-graphing.html section-substitution.html section-elimination.html review-systems-of-linear-equations.html; \
	perl -pi -e 's/https:\/\/pretextbook\.org\/css\/[\d\.]*\/colors_default\.css/css\/colors_sapphire_turquoise.css/' part-preparation-for-stem.html chapter-exponents-and-polynomials.html section-adding-and-subtracting-polynomials.html section-introduction-to-exponent-rules.html section-dividing-by-a-monomial.html section-multiplying-polynomials.html section-special-cases-of-multiplying-polynomials.html section-more-exponent-rules.html review-exponents-and-polynomials.html chapter-radical-expressions-and-equations.html section-square-and-nth-root-properties.html section-rationalizing-the-denominator.html section-radical-expressions-and-rational-exponents.html section-solving-radical-equations.html review-radical-functions-and-equations.html chapter-solving-quadratic-equations.html section-solving-quadratic-equations-by-using-a-square-root.html section-the-quadratic-formula.html section-complex-solutions-to-quadratic-equations.html section-solving-equations-in-general.html review-solving-quadratic-equations.html chapter-quantities-in-the-physical-world.html section-scientific-notation.html section-unit-conversion.html section-geometry-formulas.html section-geometry-applications.html review-quantities-in-the-physical-world.html chapter-topics-in-graphing.html section-review-of-graphing.html section-key-features-of-quadratic-graphs.html section-graphing-quadratic-expressions.html section-graphically-solving-equations-and-inequalities.html review-topics-in-graphing.html; \
	perl -pi -e 's/https:\/\/pretextbook\.org\/css\/[\d\.]*\/colors_default\.css/css\/colors_sapphire_amethyst.css/' part-preparation-for-college-algebra.html chapter-factoring.html section-factoring-out-the-common-factor.html section-factoring-by-grouping.html section-factoring-trinomials-with-leading-coefficient-one.html section-factoring-trinomials-with-a-nontrivial-leading-coefficient.html section-factoring-special-polynomials.html section-factoring-strategies.html section-solving-quadratic-equations-by-factoring.html review-factoring.html chapter-functions.html section-function-basics.html section-domain-and-range.html section-using-technology-to-explore-functions.html section-simplifying-expressions-with-function-notation.html section-technical-definition-of-a-function.html review-functions.html chapter-rational-functions-and-equations.html section-introduction-to-rational-functions.html section-multiplication-and-division-of-rational-expressions.html section-addition-and-subtraction-of-rational-expressions.html section-complex-fractions.html section-solving-rational-equations.html review-rational-functions-and-equations.html chapter-graphs-and-equations.html section-overview-of-graphing.html section-quadratic-graphs-and-vertex-form.html section-completing-the-square.html section-absolute-value-equations.html section-solving-mixed-equations.html section-compound-inequalities.html section-inequalities-graphically.html review-graphs-and-equations.html; \
	perl -pi -e 's/https:\/\/pretextbook\.org\/css\/[\d\.]*\/colors_default\.css/css\/colors_sapphire_ruby.css/' backmatter.html appendix-basic-math-review.html section-arithmetic-with-negative-numbers.html section-fractions-and-fraction-arithmetic.html section-absolute-value-and-square-root.html section-percentages.html section-order-of-operations.html section-set-notation-and-types-of-numbers.html appendix-unit-conversions.html appendix-ccogs.html ccog-mth60.html ccog-mth65.html ccog-mth95.html index-1.html; \
	perl -p0i -e 's/(<li class="(link|link active))(">\n<a href="frontmatter.html")/\1 partf\3/' *.html; \
	perl -p0i -e 's/(<li class="(link part|link part active))("><a href="part-linear-equations-and-lines.html")/\1 part1\3/' *.html; \
	perl -p0i -e 's/(<li class="(link|link active))(">\n<a href="chapter-variables-expressions-and-equations.html")/\1 part1\3/' *.html; \
	perl -p0i -e 's/(<li class="(link|link active))(">\n<a href="chapter-linear-equations-and-inequalities.html")/\1 part1\3/' *.html; \
	perl -p0i -e 's/(<li class="(link|link active))(">\n<a href="chapter-graphing-lines.html")/\1 part1\3/' *.html; \
	perl -p0i -e 's/(<li class="(link|link active))(">\n<a href="chapter-systems-of-linear-equations.html")/\1 part1\3/' *.html; \
	perl -p0i -e 's/(<li class="(link part|link part active))("><a href="part-preparation-for-stem.html")/\1 part2\3/' *.html; \
	perl -p0i -e 's/(<li class="(link|link active))(">\n<a href="chapter-exponents-and-polynomials.html")/\1 part2\3/' *.html; \
	perl -p0i -e 's/(<li class="(link|link active))(">\n<a href="chapter-radical-expressions-and-equations.html")/\1 part2\3/' *.html; \
	perl -p0i -e 's/(<li class="(link|link active))(">\n<a href="chapter-solving-quadratic-equations.html")/\1 part2\3/' *.html; \
	perl -p0i -e 's/(<li class="(link|link active))(">\n<a href="chapter-quantities-in-the-physical-world.html")/\1 part2\3/' *.html; \
	perl -p0i -e 's/(<li class="(link|link active))(">\n<a href="chapter-topics-in-graphing.html")/\1 part2\3/' *.html; \
	perl -p0i -e 's/(<li class="(link part|link part active))("><a href="part-preparation-for-college-algebra.html")/\1 part3\3/' *.html; \
	perl -p0i -e 's/(<li class="(link|link active))(">\n<a href="chapter-factoring.html")/\1 part3\3/' *.html; \
	perl -p0i -e 's/(<li class="(link|link active))(">\n<a href="chapter-functions.html")/\1 part3\3/' *.html; \
	perl -p0i -e 's/(<li class="(link|link active))(">\n<a href="chapter-rational-functions-and-equations.html")/\1 part3\3/' *.html; \
	perl -p0i -e 's/(<li class="(link|link active))(">\n<a href="chapter-graphs-and-equations.html")/\1 part3\3/' *.html; \
	perl -p0i -e 's/(<li class="(link|link active))("><a href="backmatter.html")/\1 part partb\3/' *.html; \
	perl -p0i -e 's/(<li class="(link|link active))(">\n<a href="appendix-basic-math-review.html")/\1 partb\3/' *.html; \
	perl -p0i -e 's/(<li class="(link|link active))("><a href="appendix-unit-conversions.html")/\1 partb\3/' *.html; \
	perl -p0i -e 's/(<li class="(link|link active))(">\n<a href="appendix-ccogs.html")/\1 partb\3/' *.html; \
	perl -p0i -e 's/(<li class="(link|link active))("><a href="solutions-1.html")/\1 partb\3/' *.html; \
	perl -p0i -e 's/(<li class="(link|link active))("><a href="index-1.html")/\1 partb\3/' *.html; \
	date



# make all the image files in svg format
# latex-image images
# youtube thumbnails
# interative preview images
# asymptote images
images:
	install -d $(OUTPUT)
	-rm $(IMGOUT) || :
	-rm $(OUTPUT)/preview || :
	install -d $(IMGOUT)
	install -d $(OUTPUT)/preview
	$(PTX)/script/mbx -c latex-image -f all -d $(IMGOUT) $(MAINFILE)
	$(PTX)/script/mbx -c youtube -d $(IMGOUT) $(MAINFILE)
	cd $(OUTPUT)/preview; \
	$(PTX)/script/mbx -c preview -d $(OUTPUT)/preview $(MAINFILE)
#	$(PTX)/script/mbx -c asymptote -f svg -d $(IMGOUT) $(OUTPUT)/merge.xml


###########
# Utilities
###########

# Verify Source integrity
#   Leaves "dtderrors.txt" in OUTPUT
#   can then grep on, e.g.
#     "element XXX:"
#     "does not follow"
#     "Element XXXX content does not follow"
#     "No declaration for"
#   Automatically invokes the "less" pager, could configure as $(PAGER)
check:
	install -d $(OUTPUT)
	-rm $(OUTPUT)/jingreport.txt
	-java -classpath ~/jing-trang/build -Dorg.apache.xerces.xni.parser.XMLParserConfiguration=org.apache.xerces.parsers.XIncludeParserConfiguration -jar ~/jing-trang/build/jing.jar $(PTX)/schema/pretext.rng $(MAINFILE) > $(OUTPUT)/jingreport.txt
	perl -pi -e 's/^.*permid.*\n//g' $(OUTPUT)/jingreport.txt
	perl -pi -e 's/^.*reseed.*\n//g' $(OUTPUT)/jingreport.txt
	perl -pi -e 's/^.*reading-questions.*\n//g' $(OUTPUT)/jingreport.txt
	perl -pi -e 's/^.*document-id.*\n//g' $(OUTPUT)/jingreport.txt
	perl -pi -e 's/^.*element .html.*\n//g' $(OUTPUT)/jingreport.txt
	perl -pi -e 's/^.*element .instruction.*\n//g' $(OUTPUT)/jingreport.txt
	perl -pi -e 's/^.*element .image. incomplete.*\n//g' $(OUTPUT)/jingreport.txt
	perl -pi -e 's/^.*attribute .pg-name.*\n//g' $(OUTPUT)/jingreport.txt
	perl -p0i -e 's/.*? .tabular. not allowed here.*?\n.*? .figure. incomplete.*?\n//g' $(OUTPUT)/jingreport.txt
	perl -p0i -e 's/.*? .interactive. not allowed anywhere.*?\n.*? .figure. incomplete.*?\n//g' $(OUTPUT)/jingreport.txt; \
	less $(OUTPUT)/jingreport.txt

gource:
	install -d $(OUTPUT)
	-rm $(OUTPUT)/gource.mp4 || :
	-gource --user-filter 'Stephen Simonds' --title ORCCA --key --background-image src/images/orca3.png --user-image-dir .git/avatar/ --hide filenames --seconds-per-day 0.2 --auto-skip-seconds 1 -1280x720 -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libx264 -preset veryslow -pix_fmt yuv420p -crf 23 -threads 0 -bf 0 $(OUTPUT)/gource.mp4
	-mv gource.mp4 $(OUTPUT)/gource.mp4
    
